### ISSUE TITLE
Unopened HTML tag causes exception in budoux 0.6

### ISSUE THREAD

**Issue by johncarter-phntm** [google/budoux#355]
With budoux 0.6.0

```
budoux --html "foo</p>"

Traceback (most recent call last):
  File "/home/johnc/.local/bin/budoux", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/johnc/.local/pipx/venvs/budoux/lib/python3.11/site-packages/budoux/main.py", line 187, in main
    print(_main(test))
          ^^^^^^^^^^^
  File "/home/johnc/.local/pipx/venvs/budoux/lib/python3.11/site-packages/budoux/main.py", line 171, in _main
    res = parser.translate_html_string(inputs_html)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnc/.local/pipx/venvs/budoux/lib/python3.11/site-packages/budoux/parser.py", line 102, in translate_html_string
    return resolve(chunks, html)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnc/.local/pipx/venvs/budoux/lib/python3.11/site-packages/budoux/html_processor.py", line 124, in resolve
    resolver.feed(html)
  File "/home/johnc/.pyenv/versions/3.11.3/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/home/johnc/.pyenv/versions/3.11.3/lib/python3.11/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/home/johnc/.pyenv/versions/3.11.3/lib/python3.11/html/parser.py", line 413, in parse_endtag
    self.handle_endtag(elem)
  File "/home/johnc/.local/pipx/venvs/budoux/lib/python3.11/site-packages/budoux/html_processor.py", line 84, in handle_endtag
    self.to_skip = self.element_stack.get_nowait()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnc/.pyenv/versions/3.11.3/lib/python3.11/queue.py", line 199, in get_nowait
    return self.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/johnc/.pyenv/versions/3.11.3/lib/python3.11/queue.py", line 168, in get
    raise Empty
_queue.Empty
```

**Comment by tushuhei** [comment]
Thanks for reporting this. The change is due to the non-breaking markup support we introduced at #240, where we need to track the elements in a queue.

Could you elaborate your specific use case that you want to include a close tag with no corresponding open tag? I acknowledge that we need to improve the error message, but BudouX is intended to work with a valid document fragment.

**Comment by johncarter-phntm** [comment]
Thanks. It was actually a content bug to have a missing open tag, but I thought worth reporting since it's a change in behaviour.

I don't need this to be a supported case, though maybe a nicer exception would be useful - otherwise happy for you to close as expected behaviour.

**Comment by tushuhei** [comment]
Thanks for your input. Raising a better exepction sounds like a plan.
That said, the element queue's emptiness is not enough to detect if the given HTML string is valid or not. The string like below will work with `budoux==0.6.0` CLI even thought the string is not a valid HTML.

```
budoux --html "あの空を見る限り<img>今日はとてもいい天気ですね。</p>"
```

We may need to check void elements as well to manage the element queue and the document's validity better.
@kojiishi any thoughts on this?

**Comment by kojiishi** [comment]
Thanks for reporting this issue!

I think the parser should gracefully handle unpaired close tags. Let me look into this.

For self-closing tags such as `<img>`, I think it's supported, but we don't have tests. I'll look into it too.
